### ISSUE TITLE
Installation failed on Python 3.4 Django 1.7.7 Homebrew Mac 

### ISSUE THREAD

**Issue by lisitsky** [pinax/pinax-stripe#156]
pip install git+git://github.com/buddylindsey/django-stripe-payments.git#egg=payments
Collecting payments from git+git://github.com/buddylindsey/django-stripe-payments.git#egg=payments
  Cloning git://github.com/buddylindsey/django-stripe-payments.git to /private/var/folders/3v/rcj9kh011v10fb8s9k59mgx00000gn/T/pip-build-n8fhhg9z/payments
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/3v/rcj9kh011v10fb8s9k59mgx00000gn/T/pip-build-n8fhhg9z/payments/setup.py", line 140, in <module>
        zip_safe=False,
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 14, in replacement_run
      File "/Users/el/tmp/venv-fc2/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 387, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    Complete output from command python setup.py egg_info:
    running egg_info

    creating pip-egg-info/django_stripe_payments.egg-info

    writing requirements to pip-egg-info/django_stripe_payments.egg-info/requires.txt

    writing dependency_links to pip-egg-info/django_stripe_payments.egg-info/dependency_links.txt

    writing pip-egg-info/django_stripe_payments.egg-info/PKG-INFO

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/3v/rcj9kh011v10fb8s9k59mgx00000gn/T/pip-build-n8fhhg9z/payments/setup.py", line 140, in <module>

        zip_safe=False,

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command

        cmd_obj.run()

      File "<string>", line 14, in replacement_run

      File "/Users/el/tmp/venv-fc2/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 387, in write_pkg_info

        metadata.write_pkg_info(cmd.egg_info)

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info

        self.write_pkg_file(pkg_info)

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file

        long_desc = rfc822_escape(self.get_long_description())

      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/util.py", line 470, in rfc822_escape

        lines = header.split('\n')

    TypeError: Type str doesn't support the buffer API

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3v/rcj9kh011v10fb8s9k59mgx00000gn/T/pip-build-n8fhhg9z/payments

**Comment by paltman** [comment]
Should be fixed now on `master`
