### ISSUE TITLE
Is it possible to add this module to the project directory?

### ISSUE THREAD

**Issue by robbintt** [pinax/pinax-stripe#159]
I expect to heavily extend the views and templates and think it makes more sense to have payments in my django project directory with other apps. Is this possible? Is there a better way? I get this error:

```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/djang$
/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/djang$
/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/djang$
/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/django
/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/django
/apps/config.py", line 87, in create
    module = import_module(entry)                                                      [1/600]
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robbintt/development/myproject-django/myproject/payments/__init__.py", line 4, in <mo$
ule>
    __version__ = pkg_resources.get_distribution("django-stripe-payments").version
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/pkg_r$
sources.py", line 346, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/pkg_r$
sources.py", line 225, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/pkg_r$
sources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/robbintt/development/myproject-django/venv/local/lib/python2.7/site-packages/pkg_re
sources.py", line 588, in resolve
    raise DistributionNotFound(req)
```

**Comment by paltman** [comment]
You should install external libraries using `pip`
