### ISSUE TITLE
sync_plans doesn't delete old plans

### ISSUE THREAD

**Issue by nileshbits** [pinax/pinax-stripe#229]
sync_plans doesn't delete old plans that no longer exist on the server. the code doesn't seem to be programmed to do this.

**Comment by paltman** [comment]
I think instead of deleting old plans, we should mark inactive as there remains a question what do you do with related data.  It seems like there would be plenty of site level decisions to be made.  Also, if you are manually deleting plans, i think argument could be made to manually delete plans in your database.  I'm inclined to leave that as the way to go until there is enough voting and/or justification provided for adding this to the code. 

Given this I'm removing from the 16.04 milestone.

**Comment by dgmouris** [comment]
I @paltman and @nileshbits not sure if this is related but currently I am unable to cancel a plan on the starter project.... Please let me know if this is not the place to put this comment.

**Comment by dgmouris** [comment]
In reference to the 
`Traceback (most recent call last):
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/views.py", line 185, in dispatch
    return super(Webhook, self).dispatch(*args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/views.py", line 200, in post
    message=data
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/actions/events.py", line 30, in add_event
    webhook.process()
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/webhooks.py", line 91, in process
    self.process_webhook()
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/webhooks.py", line 307, in process_webhook
    customers.sync_customer(self.event.customer, self.event.customer.stripe_customer)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/actions/customers.py", line 152, in sync_customer
    subscriptions.sync_subscription_from_stripe_data(customer, subscription)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/pinax/stripe/actions/subscriptions.py", line 157, in sync_subscription_from_stripe_data
    plan=models.Plan.objects.get(stripe_id=subscription["plan"]["id"]),
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/daniel/Documents/pin-stripe/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
`
