### ISSUE TITLE
RuntimeError: Model class django.contrib.sites.models.Site

### ISSUE THREAD

**Issue by mclean25** [pinax/pinax-stripe#258]
I get the following error when installing `pinax-stripe`, adding it to an existing projects `INSTALLED_APPS`, and running `./manage.py migrate`:

`RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

Commenting out `pinax.stripe` in my `INSTALLED_APPS` does resolve the issue, but the problem's coming from the Django source. Is it maybe a problem with the python version? (running 2.7 in this case)

**Full Error:**

```
(venv)Alexs-MacBook-Pro:cspade alex$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/alex/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/pinax/stripe/models.py", line 13, in <module>
    from .conf import settings
  File "/Users/alex/anaconda/lib/python2.7/site-packages/pinax/stripe/conf.py", line 29, in <module>
    class PinaxStripeAppConf(AppConf):
  File "/Users/alex/anaconda/lib/python2.7/site-packages/appconf/base.py", line 75, in __new__
    new_class._configure()
  File "/Users/alex/anaconda/lib/python2.7/site-packages/appconf/base.py", line 104, in _configure
    value = callback(value)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/pinax/stripe/conf.py", line 54, in configure_hookset
    return load_path_attr(value)()
  File "/Users/alex/anaconda/lib/python2.7/site-packages/pinax/stripe/conf.py", line 15, in load_path_attr
    mod = importlib.import_module(module)
  File "/Users/alex/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/alex/anaconda/lib/python2.7/site-packages/pinax/stripe/hooks.py", line 4, in <module>
    from django.contrib.sites.models import Site
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/Users/alex/anaconda/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by ossanna16** [comment]
@paltman Could you help with this?

**Comment by surfer26th** [comment]
Perhaps this stackoverflow can help you http://stackoverflow.com/questions/29635765/django-1-9-deprecation-warnings-app-label

**Comment by pawanvirsingh** [comment]
add this in you installed app 
    'pinax.blog',
    'pinax.images',

**Comment by udayposia** [comment]
**The fix**

Just add Django's Sites framework to your apps and set **SITE_ID = 1** in your settings.

`INSTALLED_APPS = [
    ...
    'django.contrib.sites',
]`

SITE_ID = 1
