### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by felixxm** [pinax/pinax-stripe#296]
Tox tests failed on the Django master:

```
ERROR: test_email_receipt_renders_amount_in_JPY_properly (pinax.stripe.tests.test_email.EmailReceiptTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pinax/pinax-stripe/.eggs/mock-2.0.0-py3.4.egg/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/pinax/pinax-stripe/pinax/stripe/tests/test_email.py", line 69, in test_email_receipt_renders_amount_in_JPY_properly
    self.assertTrue("$40000.00" in mail.outbox[0].body)

IndexError: list index out of range

======================================================================
ERROR: test_email_receipt_renders_amount_properly (pinax.stripe.tests.test_email.EmailReceiptTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pinax/pinax-stripe/.eggs/mock-2.0.0-py3.4.egg/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/pinax/pinax-stripe/pinax/stripe/tests/test_email.py", line 45, in test_email_receipt_renders_amount_properly
    self.assertTrue("$400.00" in mail.outbox[0].body)

IndexError: list index out of range
```

**Comment by felixxm** [comment]
Django prevents sending email to empty addresses (see [commit](https://github.com/django/django/commit/8858631498bca33feb2acde71f9cf6ca2884b1bd)).
